### ISSUE TITLE
Potentially valuable service but pricing...

### ISSUE THREAD

**Issue by chrislukic** [milesgranger/elevation-api-public#36]
My use case is fairly common where I need to correct paths of elevation containing between 100 - 5,000 GPS points. Google is currently both the most expensive and best quality elevation provider.  Their API allows elevation to be requested in batches of up to 500 points (limited by GET request URL length limits). So on a price per GPS point basis your service is actually double the price of Google's API.

For example. Google charges $0.005/request. So it takes me 200 requests and costs $1 to get elevations for 100 paths with 1,000 gps points per path. To use your API to achieve the same thing I would need to make 10,000 requests (10 points at a time instead of 500 with Google) and it would cost $2. Google is also, well, Google, so there's guaranteed uptime, and a high quality elevation map that's been stitched together using thousands of local sources. 

Perhaps you would consider allowing more GPS points to be calculated per request (ideally via a POST request)? If you could manage 1,000 points/request and charge 10X more per request than you do now, then your service would then cost 20% of the price of Google's elevation API, and that could potentially make it a lot more appealing to more customers.

**Comment by milesgranger** [comment]
Hi @chrislukic Thanks for this.. it actually stems from the early days.. since then it's become much more efficient. You bring up a _very_ good point with the money offsets here. I guess I was more or less banking on customers not needing to request lots of points at once, but as you point out, it cuts out a lot of potential.

Anyhow, I'll definitely re-evaluate this since the optimisations and see what how far we can push the limit.

**Comment by chrislukic** [comment]
That's great to hear. If you can increase the GPS points per request. Then you'll have earned certainly earned at least one new client, but hopefully many more. 

For my particular use case it's important to be able to include a batch of GPS points (ideally from 1k-5k points per request) in a single post request. I'll initially have 10k - 40k such paths to encode each month, but this could potentially grow 10X in the new year.  The starting cost with Google's API would be $100 - $400/mo, but at that rate, as my requirements grow I'll soon regret not rolling my own solution.  However, if I can keep costs below $100/mo initially then it's not worth the trouble to develop.

**Comment by milesgranger** [comment]
Excellent. I've given some more thought to this, and I _really_ don't want to bump the GET requests up in price, as many of my current clients choose the API mostly because they never need to get any more than 1 point per request at a time. So to 'expand' into more bulk point like requests, the best course of action, as I see it, would be to add a POST version of the endpoint which can take up to 1k points and will charge 10x the equivalent GET request.

In the current example, I'm assuming we're talking the $0.0002 /request cost (30m resolution). In such a case, you can then send 100 requests ($0.002 per) @ 1k points each for a total of $0.20 covering 100k points. 

This seems to satisfy the people who want a cheap way to make small/single point requests and people like yourself with larger workloads. Would you say this is a good way to go?

**Comment by chrislukic** [comment]
That would be a great solution from my point of view.

**Comment by chrislukic** [comment]
Have you had any thoughts about a timeline for this potential change? I'm now exploring self-hosted options, but would really much prefer to use your solution.

**Comment by milesgranger** [comment]
I had an initial prototype, but I didn't trust its performance @ 1000 batch limit. And to make the typical excuse, family, work, time in general; I can't give this the care I want to at this point in time. 

I would say certainly within a months time, I'll have this available. That's the best I can commit to, I hope that'd work for you, but if not I'd advise you to go ahead with a self hosted solution. Seems like [Open-Elevation](https://github.com/Jorl17/open-elevation) may be good option?

**Comment by chrislukic** [comment]
Thanks. I understand all to well the challenges of committing time to competing projects and priorities.
A month is reasonable timeline. Thanks for the quick response.

**Comment by chrislukic** [comment]
The demand became too pressing, and spent the day setting up our own hosted solution rather than incur additional bills from our existing providers.  Thanks, for your responsive.  I hope perhaps others may find the change to post format useful.

**Comment by milesgranger** [comment]
No worries, I'm happy you brought this to my attention. Also sorry the prototype I had at first wasn't trustworthy enough to deploy. At ~20million requests per day, I'm a bit nervous deploying something which I'm not 100% satisfied with, so my turn around is a bit slow. Anyhow, thanks again for bringing this to my attention, you've helped to make the service better! :pray:

**Comment by milesgranger** [comment]
Closing, current API now supports POST requests according to what is discussed here, *except* with a limit of 500 points; we'll see how that goes and maybe at a later date, bump it to 1000.
